drop table AppCof;
create table AppCof(id integer PRIMARY KEY NOT NULL,jsonData);
insert into AppCof values (0,'');drop table FriendData;
create table FriendData(id integer PRIMARY KEY NOT NULL,fb_id,gs_id,name,head_LocPath,head_WebPath,stage);
insert into FriendData values (1,'""','""','""','""','""',10);drop table Highscore;
create table Highscore(id integer PRIMARY KEY NOT NULL,stage_id,highscore,star_num,try_num,time_cost,skill_refresh_num,skill_bomb_num,skill_add_timer_num,skill_jewels_num,skill_unlock_num,headicon,deadpoint_I,deadpoint_X);
drop table LeaderBoard;
create table LeaderBoard(id integer PRIMARY KEY NOT NULL,boardInfo);
insert into LeaderBoard values (1,'');drop table PlayerInfo;
create table PlayerInfo(id integer PRIMARY KEY NOT NULL,stage,Life,MaxLifeTime,MaxLife,Infinite_time,Gold,Redraw,Bomb,Clock,Jewel,Unchain,device_id,player_update,highscore);
insert into PlayerInfo values (1,1,5,'0',5,'0',50,0,0,0,0,0,'0','0','0');drop table ShopOrder;
create table ShopOrder(id integer PRIMARY KEY NOT NULL,ItemOrder,Tag);
insert into ShopOrder values (101,1,0);
insert into ShopOrder values (102,2,0);
insert into ShopOrder values (103,3,1);
insert into ShopOrder values (104,4,0);
insert into ShopOrder values (105,5,0);
insert into ShopOrder values (106,6,2);
insert into ShopOrder values (201,7,0);
insert into ShopOrder values (202,8,0);
insert into ShopOrder values (203,9,0);